version: '3'
services:
  course-service:
    build: .
    depends_on:
      - db
    ports:
     - "5001:5001"
    command:
      node src/app
    volumes:
      - .:/code
    links:
      - db
    environment:
      - DOCKER=true

  db:
    image: "postgres:11"
    container_name: "courses_postgres"
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'postgres'
      - POSTGRES_DB:'courses'
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
