version: '3'
services:
  courses-service:
    container_name: "courses-service"
    depends_on:
      - courses-db
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - courses

  courses-db:
    build:
      context: .
      dockerfile: ./Dockerfile-db
    container_name: "courses-db"
    networks:
      - courses
    volumes:
      - courses-dbdata:/var/lib/postgresql/data

volumes:
  courses-dbdata:

networks:
  courses:
