version: '3'
services:
  courses-service:
    container_name: "courses-service"
    ports:
      - "127.0.0.1:5001:5001"
    depends_on:
      - courses-db
    build:
      context: .
      dockerfile: ./Dockerfile

  courses-db:
    build:
      context: .
      dockerfile: ./Dockerfile-db
    container_name: "courses-db"
    volumes:
      - courses-dbdata:/var/lib/postgresql/data

volumes:
  courses-dbdata:
